### ISSUE TITLE
abstracts dom and css for gioui

### ISSUE THREAD

**Issue by gedw99** [touchmarine/to#1]
As per reddit conversion, here is the link to the project that shows an approach to abstract the DOM and CSS 

https://github.com/npillmayer/giocomp

**Comment by touchmarine** [comment]
Thank you for the link. Adding the [reddit thread](https://old.reddit.com/r/golang/comments/rh8nfw/i_wrote_a_lightweight_markup_language_in_go_sorta/howgq81/) for posterity.

For any passerby, a TLDR: the link shows an example usage of [Gio UI](https://gioui.org/)—a Go GUI library, pointed out by @gedw99, that could be used to implement an editor. It is not directly related to Touch.
