### ISSUE TITLE
Playground (and touchlabs.io) needs a valid  SSL/TLS server certificate.   

### ISSUE THREAD

**Issue by vassudanagunta** [touchmarine/to#3]
This is what users who visit touchlabs.io using Safari sees:

<img width="749" alt="Screen Shot 2022-07-19 at 10 42 43 AM" src="https://user-images.githubusercontent.com/2830093/179778741-a42b3a4a-59fb-4baa-b147-ba508c2dc08a.png">

There are many avenues to getting a free certificate. A web search will show you many. 

Alternatively do not use or require HTTPS.

**Comment by ousia** [comment]
@touchmarine, I guess the certificate the site is using needs renewal.

**Comment by ousia** [comment]
BTW, the certificate for https://thunkhq.com needs renewal too.

**Comment by touchmarine** [comment]
Renewed both (renewal cron didn't run). Thanks both for reporting!
